name: serverCI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - server/src**

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: debug
        run: ls -al
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.working-directory }}
          file: ${{ env.working-directory }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: snowdelver/eweapi:${{ github.sha }}
